### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by ryandhikacc** [thebrumby/HotWalletClaimer#22]
After running bots for 72 hours straight, bots encountered strange error:
![image](https://github.com/thebrumby/HotWalletClaimer/assets/159438475/1bd7b03a-78b5-4ae2-8282-bd86ab13d6ae)
Error logs:
![image](https://github.com/thebrumby/HotWalletClaimer/assets/159438475/4b11409a-bed3-4433-aeec-a135b70d4e24)

Tried `pm2 restart all` and `git pull` but issues still persist.

**Comment by thebrumby** [comment]
Many apologies! That was my fault.

In tidying the repository, I moved all the apps/games into a /games/ folder. I just realized if someone had active PM2 processes, and does a Git Pull - that while new sessions should work fine, it will break any existing PM processes raised from the original location.

To avoid making a new instance for everything, you can create simlinks :)

```
ln -s ./games/hot.py hot.py
ln -s ./games/cold.py cold.py
ln -s ./games/wave.py wave.py
ln -s ./games/tree.py tree.py
ln -s ./games/vertus.py vertus.py
```

**Comment by ryandhikacc** [comment]
Quick replies, thanks!
![image](https://github.com/thebrumby/HotWalletClaimer/assets/159438475/269a81b4-be19-4ade-9b9c-a2bfebd87f1d)
`pm2 restart all` and now it works perfectly again! Thanks

**Comment by thebrumby** [comment]
Or more accurately, as well as tidying it up, the Docker setup will check git twice a day, update the games folder if there were changes, and then automatically restart only the scripts that changed (if any) - so that's why I was messing about with the structure :P

**Comment by ryandhikacc** [comment]
ugh, sorry, i thought everything was working already, but this error.....
![image](https://github.com/thebrumby/HotWalletClaimer/assets/159438475/13043438-93eb-4fe2-a304-f52ca9bbbcbc)

**Comment by thebrumby** [comment]
Thanks for highlighting it! 

Some of the games require to see the mouse moving before they believe an action is by a human (makes a lot of sense that the pointer can't magically jump to the right spot every time), but it seems the movement I built in is moving some of the Telegram targets out-of-range. 

I pushed a smaller update that excludes the mouse movement, which I hope will resolve the issue :) I did a fresh install on docker and they all tested OK, but let me know how you get on.

**Comment by ryandhikacc** [comment]
pull then restart, but still showing this error on some saved sessions (not all sessions)
![image](https://github.com/thebrumby/HotWalletClaimer/assets/159438475/d89a315c-4648-4df3-8482-e78a0f7214f4)

**Comment by thebrumby** [comment]
OK, I wonder if these sessions got corrupted? selenium doesn't like getting disturbed mid-session.

If you run it with the debug option turned on, you can see the virtual screenshots of what's happening in the process. These would appear in `./screenshots./Wave:Wallet12` for example. Maybe the QR code is back showing, meaning you'd need to re-enter the seed phrase again. 

Alternatively, you can jump straight to the step of running the `./remove-process.sh` command. You might need to make it executable first with `chmod +x remove-process.sh`. If you select option 1 to remove an active process it will remove it from PM2 and remove the named folders (just for that one session) in selenium, screenshots, and backup.

Let me know how you get on :)

**Comment by ryandhikacc** [comment]
ok, after trying to restart "corrupted session". new problem arise 😅, although the wave bot is working fine (same telegram session) check this debug screenshot
![image](https://github.com/thebrumby/HotWalletClaimer/assets/159438475/bebab707-d93c-49d6-899a-4a5e70ccf3a5)

**Comment by thebrumby** [comment]
Is there a chance you had the HOT wallet page open in your Telegram app or Telegram Web, that interrupted the flow?

**Comment by ryandhikacc** [comment]
> Is there a chance you had the HOT wallet page open in your Telegram app or Telegram Web, that interrupted the flow?

There is not, i only open telegram for login and checking otp

**Comment by ryandhikacc** [comment]
It looks like restoring from the saved session doesn't work. I tried restoring using the saved session from Wave, and the Wave session is fine
![image](https://github.com/thebrumby/HotWalletClaimer/assets/159438475/37edc2a0-6a0c-473f-9192-7fab6fdd7196)

**Comment by thebrumby** [comment]
Yup, the saved TG backup got corrupted too. If you run `./remove-process.sh` and select option 2, pick the number for the TG account that got corrupted. You might also need to run option 1 or 2 to remove the hot account if it got all the way through setup.

Then run `./launch.sh`, skip changing the settings, enter your required session name, and when it asks for a Telegram account, press "n" to create a new one, and authenticate again.

As an FYI, those games that log in via seed phrase don't "need" to be run from separate TG accounts if you don't want to. I have a **lot** of hot accounts all running from one TG account.

**Comment by ryandhikacc** [comment]
Well, I've tried importing HOT seed phrases on one Telegram account before and then claiming all the accounts from one Telegram (via mobile telegram), and I ended up losing the account (lost in terms of the account getting a rotten wood penalty for suspected multi-account mining, I guess?). So, for security reasons, I separated the TG accounts. Maybe it's not your time yet, or I'm just unlucky.

Back to the main topic, I had to start all over again to log in, and it seems to be running normally now. I hope there are no more errors because previously the script ran smoothly for 72 hours. Thanks again for the script😁

**Comment by thebrumby** [comment]
I saw before that if people imported into the add account in the GUI that gave the "rotten wood" thing, but I never had a problem with separate sessions using the script - as you say, maybe my time will come!

For sure, the initial problem was me moving the location of the games - which will be a one-time thing. I'm making room for the two upcoming games that I hope to release today or tomorrow!
